name: test_aneurysm
channels:
  - simpleitk
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - joblib=0.17
  - nibabel=3.2
  - simpleitk=2.0
  - pandas=1.2
  - scipy=1.6
  # - pip:
  #     - numpy==1.19.5  # Compatible with TensorFlow 2.4
  #     - connected-components-3d==3.2
  #     - scikit-image==0.18
  #     - opencv-python-4.5.3.56
  #     - antspyx==0.2
  #     - tensorboard==2.4
  #     - tensorboard-plugin-wit==1.6
  #     - tensorflow==2.4
  #     - matplotlib==3.2
